### ISSUE TITLE
Why left Polkadot? 

### ISSUE THREAD

**Issue by TingALin** [tearust/teaproject#133]
Hi there,

I am impressed by the tea project itself with the technical architecture, and the reason I noticed this project is I was studying Polkadot and saw Tea somewhere in the ecosystem. And after awhile I noticed Tea project is not using Polkadot as the layer 1 anymore, and I am curious is it because there are security issues for this?

**Comment by kevingzhang** [comment]
TEA Project is a special type of layer2. It has its own state machine and maintain its state on layer2 instead of layer1. Most other layer2 project only execute transactions and send the final (rolled up) state change to layer1, then layer1 verify the state changes valid for updating layer 1 state. TEA Project doesn't require all of these, it only need layer1 for a few basic security logic such as state machine nodes voting and bridge between two layer2 for assets transfer.

In this case, TEA Project doesn't need a lot of features from layer1 as other layer2 projects did. We can work with any layer1, even BTC who has very little programmable logic. 

In this case, DOT, ETH or BTC make no difference to us. What features we need from layer1 are:
- Widely used for majority of users
- Basic logic (such as smart contract or mini scripts) features but stable and reliable
- Popular assets such as stable coins that TEA users can use to exchange or topup/withdraw

In this case, ETH is good enough for our use, even BTC works. I know DOT is far more advanced in many prospect, it just over qualified. On the other hand, DOT is not as popular as ETH or BTC. Even the basic stable coin is not widely used in DOT community. This is one of the major reason we finally gave up DOT. 

There is not any reason related to security. I believe DOT is secure enough, but we just do not need those features brought by DOT. In our tenet, simple and basic is better than complex and advanced. So we switched to ETH after the first two years with DOT.

Please add your comments below

**Comment by TingALin** [comment]
two layer2? what would be the other beside Tea runtime?

**Comment by kevingzhang** [comment]
Sorry, typo. i meant "two layers" not "two layer2".
