### ISSUE TITLE
TApp token value calculation is not correct on leader board

### ISSUE THREAD

**Issue by lxm218** [tearust/teaproject#78]
stake token was valued based on selling price. User can easily distribute 10000 tokens to host (including themselves) to get higher ranking. see these 2 accounts in screenshot ranked no.2 and 3: 

![image](https://user-images.githubusercontent.com/12605218/136135302-7e8de2d6-b4b9-4f6e-9f72-bd43e1794fac.png)

**Comment by kevingzhang** [comment]
the root cause is that when the leader board calculation assets, the staking token(those token earned from hosting a fixed-token-tapp) is added to the investment token, then multiply the selling price. This makes a flaw that once you have a huge amount of staking token, regardless the tapp makes revenue or not, you will be rich on the leader board.

A hotfix will be delivered to the blockchain in few hours. This would be a runtime upgrade without restart blockchain. Unlike Ethereum, TEA can do upgrades without fork (soft or hard forks).
